# Generated by Django 2.1.5 on 2019-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaningDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=200, verbose_name='Задача')),
                ('expirationTime', models.DateTimeField(verbose_name='Время задачи')),
                ('priority', models.CharField(max_length=50, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Задача на день',
                'verbose_name_plural': 'Задачи на день',
            },
        ),
    ]
