# Generated by Django 2.1.5 on 2019-02-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_planingday_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Приоритет')),
            ],
        ),
        migrations.AlterField(
            model_name='planingday',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.TaskPriorities', verbose_name='Приоритет'),
        ),
    ]
