# Generated by Django 2.1.5 on 2019-02-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190211_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpriorities',
            options={'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
    ]
