# Generated by Django 2.1.5 on 2019-02-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_taskpriorities_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpriorities',
            name='order',
        ),
    ]
