# Generated by Django 2.1.5 on 2019-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_taskpriorities_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpriorities',
            name='order',
            field=models.IntegerField(default=1, unique=True, verbose_name='Порядок следования'),
            preserve_default=False,
        ),
    ]
