# Generated by Django 2.1.5 on 2019-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_taskpriorities_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpriorities',
            name='order',
            field=models.IntegerField(unique=True, verbose_name='Порядок'),
        ),
    ]
