# Generated by Django 2.1.4 on 2019-02-15 16:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190211_1607'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taskpriorities',
            managers=[
                ('test', django.db.models.manager.Manager()),
            ],
        ),
    ]
