# Generated by Django 2.1.4 on 2019-02-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190215_1800'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taskpriorities',
            managers=[
            ],
        ),
    ]
