# Generated by Django 2.1.4 on 2019-02-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190215_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpriorities',
            options={'ordering': ('order',), 'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
    ]
