# Generated by Django 2.1.4 on 2019-02-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190216_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpriorities',
            options={'ordering': ['order'], 'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
    ]
