# Generated by Django 2.1.4 on 2019-02-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190216_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaningDay',
            new_name='DayTasks',
        ),
    ]
