# Generated by Django 2.1.7 on 2019-03-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190216_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytasks',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='priority', to='app.TaskPriorities', verbose_name='Приоритет'),
        ),
    ]
