# Generated by Django 2.1.7 on 2019-03-23 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190323_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytasks',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Описание задачи'),
            preserve_default=False,
        ),
    ]
